
title: Opendoc Theme
description: Jekyll Theme for Opendocs
plugins:
  - jekyll-include-cache
baseurl: ''
kramdown:
  auto_id_stripping: true
repository: opendocsg/opendoc-theme
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
fast_build: true
offline_search_only: false


subtitle: this is a subtitle
order:
  - contribute.md
  - import-files.md

google_analytics: 'UA-113717369-5'
styling_options:
  primary_brand_color: '#17335f'
  opendoc_logo_path: /assets/images/logo-full.png
  logo_path: /assets/images/logo-full.png
  feedback_url: null
