
title: Opendoc Theme
description: Jekyll Theme for Opendocs
plugins:
  - jekyll-include-cache
baseurl: ''
kramdown:
  auto_id_stripping: true
repository: opendocsg/opendoc-theme
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
PDF_storage_URL: https://opendoc-theme-pdf.s3-ap-southeast-1.amazonaws.com/opendoc-theme
fast_build: true
offline_search_only: false


subtitle: this is a subtitle
order:
  - contribute.md
  - import-files.md

google_analytics: 'UA-113717369-5'
styling_options:
  primary_brand_color: '#17335f'
  logo_path: /assets/images/opendoc-logo-full.svg
  logo_url: https://opendoc.sg
  feedback_url: null
