
title: Opendoc Theme
description: Jekyll Theme for Opendocs
plugins:
  - jekyll-include-cache
baseurl: ''
kramdown:
  auto_id_stripping: true
repository: opendocsg/opendoc-theme
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg

subtitle: this is a subtitle
order:
  - contribute.md
  - import-files.md

styling_options:
  primary_brand_color: '#990921'
  opendoc_logo_path: /assets/images/logo-full.png
  logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5bbdc1959d1bb0000f818d8c
